name: CI/CD

on: [push]

jobs:
  Test:
    name: Unit Tests
    runs-on: macos-13

    steps:
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Tests
        run: |
          echo "Running Unit Tests"
          xcodebuild test -scheme PrivateTestingMacroClient -destination 'platform=iOS Simulator,name=iPhone 15'
          echo "Tests Complete"
        env:
          TERM: xterm-256color
